vimc/montagu-webapps

app/src/main/admin/components/ModellingGroups/ListOfUsers.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Admin/GroupAdminContent.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Admin/GroupAdminPage.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Details/GroupAdminSummary.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ModellingGroupDetailsContent.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ViewModellingGroupDetailsPage.tsx
app/src/main/shared/components/Helpers.tsx
app/src/main/shared/stores/AuthStoreBase.ts
app/src/test/admin/components/ModellingGroups/List/ViewAllModellingGroupsPageTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/GroupAdminContentTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/GroupAdminPageTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/GroupAdminSummaryTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/ListOfUsersTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-358

Display users' names in Modelling Group Details pages

---

app/src/main/report/sources/ReportingSource.ts
app/src/main/shared/sources/Source.ts
app/src/test/report/fetch/ReportingFetchHelper.ts
app/src/test/shared/fetch/helpers.ts

Hi Alex,
I felt like I wasn't communicating clearly on the [VIMC-417 PR](https://github.com/vimc/montagu-webapps/pull/14), so I thought I'd just write the changes I was suggesting. In both cases the amount of duplication is reduced.
If you're happy with them, you can click merge on this PR, which will merge the changes into the main i417 branch. I'll then give things another look over there before merging into master.

Suggested refactors to Alex's work on VIMC-417

---

app/src/main/report/README.md

updated README to reflect changes to running the APIs for web dev

updated readme.md

---

app/docker/build-images.sh
app/package.json
app/src/main/admin/index.html
app/src/main/admin/index.tsx
app/src/main/contrib/index.html
app/src/main/contrib/index.tsx
app/src/main/report/index.html
app/src/main/report/index.tsx
app/src/main/shared/settings/docker.ts
app/webpack.common.js
app/webpack.config.js

This cannot be merged until #18 is merged, as I branched off of that.
https://vimc.myjetbrains.com/youtrack/issue/VIMC-429

Adapt reporting portal to work in real deployment

---

app/docker/build-images.sh
app/package.json
app/src/main/admin/index.html
app/src/main/admin/index.tsx
app/src/main/contrib/index.html
app/src/main/contrib/index.tsx
app/src/main/report/index.html
app/src/main/report/index.tsx
app/webpack.common.js

https://vimc.myjetbrains.com/youtrack/issue/VIMC-399
To test this, checkout i399 on the main Montagu repo and run `./src/deploy.py`.
As part of this, I discovered that the TeamCity task was tagging images with branch and commit, but was only pushing the commit tags. So I fixed that too.

Links to portals don't work

---

app/src/main/contrib/actions/DemographicActions.ts
app/src/main/contrib/components/Responsibilities/Demographics/DemographicOptions.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
app/src/main/contrib/components/Responsibilities/Demographics/SourceControl.tsx
app/src/main/contrib/components/Responsibilities/Responsibilities.css
app/src/main/contrib/sources/DemographicSource.ts
app/src/main/contrib/stores/DemographicStore.ts
app/src/test/contrib/components/Responsibilities/Demographics/DemographicOptionsTests.tsx
app/src/test/contrib/components/Responsibilities/Demographics/DownloadDemographicsContentTests.tsx
app/src/test/contrib/fetch/DemographicFetchTests.ts
app/src/test/contrib/stores/DemographicStoreTests.ts
app/src/test/shared/fetch/helpers.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-511

User can select data source for demographic data

---

app/src/main/contrib/actions/DemographicActions.ts
app/src/main/contrib/components/Responsibilities/Demographics/DemographicOptions.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
app/src/main/contrib/components/Responsibilities/Demographics/SourceControl.tsx
app/src/main/contrib/components/Responsibilities/Responsibilities.css
app/src/main/contrib/sources/DemographicSource.ts
app/src/main/contrib/stores/DemographicStore.ts
app/src/test/contrib/components/Responsibilities/Demographics/DemographicOptionsTests.tsx
app/src/test/contrib/components/Responsibilities/Demographics/DownloadDemographicsContentTests.tsx
app/src/test/contrib/fetch/DemographicFetchTests.ts
app/src/test/contrib/stores/DemographicStoreTests.ts
app/src/test/mocks/mockModels.ts
app/src/test/shared/fetch/helpers.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-462
I can't prove this works, because of the bug with VIMC-461, but it seems to generate the right URLs. Up to you whether you review and merge it now or later.

Portal allows user to select gender option for dataset where available

---

app/src/main/admin/actions/UserActions.ts
app/src/main/admin/components/Users/Create/CreateUserForm.ts
app/src/main/admin/components/Users/Create/CreateUserForm.tsx
app/src/main/admin/components/Users/Create/CreateUserFormStore.ts
app/src/main/admin/components/Users/Create/CreateUserSection.tsx
app/src/main/admin/components/Users/List/ViewAllUsersPage.tsx
app/src/main/admin/sources/UserSource.ts
app/src/main/admin/stores/UserStore.ts
app/src/main/shared/FormHelpers.ts
app/src/main/shared/Validation.ts
app/src/main/shared/components/Login/LoginForm.ts
app/src/main/shared/sources/Fetcher.ts
app/src/main/shared/sources/Source.ts
app/src/main/shared/styles/forms.css
app/src/test/Sandbox.ts
app/src/test/admin/components/Users/Create/CreateUserFormTests.tsx
app/src/test/admin/components/Users/Create/CreateUserSectionTests.tsx
app/src/test/admin/fetch/UserFetchTests.ts
app/src/test/admin/stores/UserStoreTests.ts
app/src/test/shared/FormHelperTests.ts
app/src/test/shared/fetch/helpers.ts
app/src/test/shared/validation/MultiValidationTests.ts
app/src/test/shared/validation/RequiredTests.ts
app/src/test/shared/validation/UsernameFormatTests.ts
app/src/test/shared/validation/ValidationTestBaseClass.ts
app/src/test/shared/validation/ValidationTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-160

Create new user

---

app/src/main/admin/components/Users/Create/CreateUserForm.tsx
app/src/main/admin/components/Users/Create/CreateUserFormStore.ts
app/src/test/admin/components/Users/Create/CreateUserFormTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-527
Depends on https://vimc.myjetbrains.com/youtrack/issue/VIMC-160

I527 autocomplete username

---

app/src/main/contrib/components/ChooseAction/ChooseTouchstone.css
app/src/main/contrib/components/ChooseGroup/ChooseGroup.css

https://vimc.myjetbrains.com/youtrack/issue/VIMC-559
https://vimc.myjetbrains.com/youtrack/issue/VIMC-589

Remove fixed widths

---

app/src/main/contrib/components/Responsibilities/Coverage/CoverageSetList.tsx
app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DemographicOptions.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewPage.tsx
app/src/main/contrib/stores/DemographicStore.ts
app/src/main/shared/styles/common.css
app/src/test/contrib/components/Responsibilities/Demographics/DemographicOptionsTests.tsx
app/src/test/contrib/fetch/DemographicFetchTests.ts
app/src/test/contrib/stores/DemographicStoreTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-601

Documentation for montagu contribution portal

---

app/src/main/report/components/Artefacts/Artefact.tsx
app/src/main/report/components/Artefacts/ArtefactsList.tsx
app/src/main/shared/models/reports/Artefact.ts
app/src/test/mocks/mockModels.ts
app/src/test/report/components/Artefacts/ArtefactItemTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-597

Just display a link to the first artefact filename.

---

app/src/main/report/components/Artefacts/Artefact.tsx
app/src/main/report/components/Artefacts/ArtefactsList.tsx
app/src/main/report/components/Versions/VersionDetails.tsx
app/src/main/report/styles/reports.css
app/src/test/mocks/mockModels.ts
app/src/test/report/components/Artefacts/ArtefactItemTests.tsx
app/src/test/report/components/Artefacts/ArtefactsListTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-608

Reporting portal is returning only first artefact of each type

---

app/src/main/shared/components/ErrorLog/ErrorLog.css
app/src/main/shared/components/ErrorLog/ErrorLog.tsx
app/src/main/shared/stores/NotificationStore.ts
app/src/test/shared/actions/NotificationActionTests.ts
app/src/test/shared/components/ErrorLogTests.tsx
app/src/test/shared/stores/NotificationStoreTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-615

Stacking error messages

---

app/package-lock.json
app/package.json
app/src/main/admin/index.html
app/src/main/admin/index.tsx
app/src/main/shared/styles/common.css
app/webpack.common.js
app/webpack.config.js

get latest bootstrap with npm

---

app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContent.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-781

Add disclaimer message.

---

app/src/main/report/index.html

This fixes the body styling, and will get used further in the UI refresh.

add bootstrap to reporting portal

---

app/src/main/contrib/actions/CoverageSetActions.ts
app/src/main/contrib/actions/DemographicActions.ts
app/src/main/contrib/components/NavBar/NavBar.css
app/src/main/contrib/components/Responsibilities/Coverage/CoverageSetComponent.tsx
app/src/main/contrib/components/Responsibilities/Coverage/CoverageSetList.tsx
app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DemographicOptions.tsx
app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
app/src/main/contrib/components/Responsibilities/Demographics/FormatControl.tsx
app/src/main/contrib/components/Responsibilities/Demographics/GenderControl.tsx
app/src/main/contrib/components/Responsibilities/DownloadDataTitle.tsx
app/src/main/contrib/components/Responsibilities/FormatControl.tsx
app/src/main/contrib/components/Responsibilities/Overview/List/ResponsibilityList.tsx
app/src/main/contrib/index.html
app/src/main/contrib/sources/CoverageTokenSource.ts
app/src/main/contrib/sources/DemographicSource.ts
app/src/main/contrib/stores/DemographicStore.ts
app/src/main/contrib/stores/ResponsibilityStore.ts
app/src/main/shared/components/PageWithHeader/PageWithHeader.css
app/src/test/contrib/components/Responsibilities/Demographics/DemographicOptionsTests.tsx
app/src/test/contrib/components/Responsibilities/Demographics/DownloadDemographicsContentTests.tsx
app/src/test/contrib/components/Responsibilities/DownloadCoverageComponentTests.tsx
app/src/test/contrib/fetch/CoverageTokenFetchTests.ts
app/src/test/contrib/fetch/DemographicFetchTests.ts
app/src/test/contrib/stores/DemographicStoreTests.ts
app/src/test/contrib/stores/ResponsibilityStoreTests.ts

Brought Bootstrap in to contrib portal to style these components which involved some style tweaks in other components to get it all looking right

Add wide/long format options to portals

---

app/src/main/shared/actions/NavActions.ts
app/src/main/shared/components/NavBar/NavBar.tsx
app/src/main/shared/components/PageWithHeader/PageWithHeader.tsx
app/src/test/shared/components/BreadcrumbTests.tsx
app/src/test/shared/components/NavBarTests.tsx
app/src/test/shared/components/PageWithHeaderTests.tsx
app/src/test/shared/stores/NavStoreTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-397

More tests for the breadcrumbs work

---

app/src/main/report/components/Reports/ReportList.tsx
app/src/main/report/components/Reports/ReportListItem.tsx
app/src/main/shared/models/reports/Report.ts
app/src/test/report/components/ReportListItemTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-867

List reports by descriptive name rather than id

---

app/src/main/report/components/Versions/VersionInfoPage.tsx

I have manually tested this and it works in a local Montagu deploy.

Prepend publicPath when redirecting.

---

app/src/main/report/components/Reports/ReportPage.tsx
app/src/main/report/components/Reports/ReportPageTitle.tsx
app/src/main/shared/models/Lookup.ts
app/src/test/report/components/Reports/ReportPageTitleTests.tsx

Merge https://github.com/vimc/montagu-webapps/pull/78 first.
Part of the https://vimc.myjetbrains.com/youtrack/issue/VIMC-868 work.

Use display name in report page title

---

app/src/main/report/components/DraftStamp.tsx
app/src/main/report/components/Reports/ReportDetails.tsx
app/src/main/shared/models/reports/Report.ts
app/src/test/mocks/mockModels.ts
app/src/test/report/components/DraftStampTests.tsx
app/src/test/report/components/Reports/ReportDetailsTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-865

Visual indication of published status

---

app/scripts/make-build-env.sh
app/scripts/make-integration-tests-image.sh

i997: Lock short commits to 7 characters

---

app/src/main/report/components/Reports/ReportPageTitle.tsx
app/src/test/report/components/Reports/ReportPageTitleTests.tsx

to fix this i needed to fix the way version details are set in PageTitle component

i978 - Display name is not rendered in title on report page

---

app/src/main/report/components/FileDownloadLink.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1025
Tested and working in latest Chrome and Firefox.

i1025: Anchor tag attributes

---

app/docker/nginx.default.conf
app/webpack.common.js

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1007

Move resources into subfolder

---

app/src/main/contrib/components/ChooseAction/TouchstoneList.css
app/src/main/contrib/components/ChooseAction/TouchstoneList.tsx
app/src/test/contrib/components/ChooseAction/TouchstoneListTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1172

i1172: One button per open touchstone

---

app/src/main/report/components/Reports/ReportPage.tsx
app/src/main/shared/actions/NavActions.ts
app/src/main/shared/components/PageWithHeader/PageWithHeader.tsx
app/src/main/shared/stores/NavStore.ts
app/src/test/shared/NavigationTests.ts
app/src/test/shared/components/BreadcrumbTests.tsx
app/src/test/shared/components/NavBarTests.tsx
app/src/test/shared/stores/NavStoreTests.ts

rely fully on initialise function in NavActions to create breadcrumb, making it canonical
removed navigate functionality
removed some tests

I1005 - Breadcrumb on report page should show version

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetForm.tsx
app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
app/src/main/shared/components/Form.tsx
app/src/test/contrib/components/Responsibilities/CurrentEstimateSetSummaryTests.tsx
app/src/test/contrib/components/Responsibilities/Uploads/CreateEstimateSetTests.tsx
app/src/test/contrib/components/Responsibilities/Uploads/FormTests.tsx

also moved Form component to shared folder, where it belongs

updated terminology

---

app/src/main/contrib/components/Responsibilities/ModelRunParameters/ModelRunParameterSetsList.tsx
app/src/test/contrib/components/ChooseAction/ChooseActionPageTests.tsx
app/src/test/contrib/components/Responsibilities/Demographics/DownloadDemographicsPageTests.tsx
app/src/test/contrib/components/Responsibilities/DownloadCoveragePageTests.tsx
app/src/test/contrib/components/Responsibilities/ModelRunParameters/ModelRunParametersPageTests.tsx
app/src/test/contrib/components/Responsibilities/ResponsibilityOverviewPageTests.tsx
app/src/test/contrib/components/Responsibilities/Uploads/UploadEstimatesPageTests.tsx
app/src/test/mocks/mocks.ts

fixed warnings related to currentTouchstone was not defined

i1151 - fix  some warnings in tests caused by components

---

app/src/main/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetForm.tsx
app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContent.tsx
app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
app/src/test/contrib/components/Responsibilities/Uploads/UploadBurdenEstimateFormTests.tsx

* hide forms after a successful upload, i.e. while the success message is showing
* change language slightly to emphasise the 2 step process
* 96 countries -> 98

burden estimate form tweaks

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/sources/TouchstoneSource.ts
app/src/main/contrib/stores/ResponsibilityStore.ts
app/src/test/contrib/components/ChooseAction/ChooseActionPageTests.tsx
app/src/test/contrib/components/Responsibilities/Demographics/DownloadDemographicsPageTests.tsx
app/src/test/contrib/components/Responsibilities/DownloadCoveragePageTests.tsx
app/src/test/contrib/components/Responsibilities/ModelRunParameters/ModelRunParametersPageTests.tsx
app/src/test/contrib/components/Responsibilities/ResponsibilityOverviewPageTests.tsx
app/src/test/contrib/components/Responsibilities/Uploads/UploadEstimatesPageTests.tsx
app/src/test/contrib/fetch/TouchstoneFetchTests.ts
app/src/test/mocks/mockEndpoints.ts

Only show touchstones where selected modelling group has a responsibility

i562 - Only show touchstones where selected modelling group has a responsibility

---

app/src/main/contrib/sources/TouchstoneSource.ts
app/src/test/contrib/fetch/TouchstoneFetchTests.ts

do not cache touchstones list fetch

i562 - do not cache touchstones list fetch

---

app/src/main/shared/styles/common.scss

i1186 - Dropdowns have squashed buttons in Firefox

i1186 - Dropdowns have squashed buttons in Firefox

---

app/package-lock.json
app/package.json
app/src/@types/globals.d.ts
app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/components/Responsibilities/ModelRunParameters/ModelRunParameterSetsList.tsx
app/src/test/contrib/components/Responsibilities/ModelRunParameters/ModelRunParameterSetsListTests.tsx

I1209 - Allow user to download metadata blob that uniquely identifies model run parameter set

I1209 - Allow user to download metadata blob that uniquely identifies model run parameter set

---

app/package-lock.json
app/src/main/contrib/components/Responsibilities/Guidance/ResponsibilityGuidanceModelOutputs.tsx

I've printed off a copy of the new page for @kimwoodruff to review (so she doesn't have to wait for us to merge this in and deploy to UAT to review). So no need to review every word here, I think.

Update model-outputs guidance.

---

app/src/main/admin/components/ModellingGroups/SingleGroup/Details/GroupMembersSummary.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ModellingGroupDetailsContent.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Members/GroupMembersContent.tsx
app/src/main/shared/stores/AuthStoreBase.ts
app/src/test/admin/components/ModellingGroups/SingleGroup/GroupMembersContentTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/GroupMembersSummaryTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-748
Also add user link.
First review #166.

i748: Don't show edit users link for non admins 

---

app/docker/dev.dockerfile
app/docker/shared-build-env.dockerfile

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1449

i1449: Use node 8

---

app/docker/shared-build-env.dockerfile
app/src/main/admin/components/ModellingGroups/ListOfUsers.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Members/AddMember.tsx
app/src/main/admin/components/ModellingGroups/SingleGroup/Members/GroupMembersPage.tsx
app/src/test/Sandbox.ts
app/src/test/admin/components/ModellingGroups/SingleGroup/AddMemberTests.tsx
app/src/test/admin/components/ModellingGroups/SingleGroup/ListOfUsersTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1420

i1420: Alphabetize user list and dropdown

---

app/package.json
app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
app/src/main/shared/components/UploadFileForm.tsx
app/src/main/shared/validation/FileValidationHelpers.tsx
app/src/test/Sandbox.ts
app/src/test/mocks/mockRemote.ts
app/src/test/shared/components/UploadFormTests.tsx
app/src/test/shared/validation/FileValidationHelperTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1422
First review #177.

i1422: Check file extension is .csv before submitting estimate form 

---

app/src/main/contrib/components/Responsibilities/Guidance/Demographics/ResponsibilityGuidanceKosovo.tsx
app/src/main/contrib/components/Responsibilities/Guidance/Demographics/ResponsibilityGuidanceMarshallIslands.tsx
app/src/main/contrib/components/Responsibilities/Guidance/Demographics/ResponsibilityGuidanceNeonatalMortality.tsx
app/src/main/contrib/components/Responsibilities/Guidance/Demographics/ResponsibilityGuidanceOver80.tsx
app/src/main/contrib/components/Responsibilities/Guidance/Demographics/ResponsibilityGuidanceTuvalu.tsx

Should only be merged after 
https://github.com/vimc/montagu/pull/81

use nginx served paths for iframe srcs and remove html folder

---

app/package-lock.json
app/src/main/contrib/actionTypes/ModellingGroupsTypes.ts
app/src/main/contrib/actions/modellingGroupsActions.ts
app/src/main/contrib/components/ChooseGroup/ChooseGroupContent.tsx
app/src/main/shared/components/Login/LoggedInUserBox.tsx
app/src/main/shared/components/Login/LoginForm.tsx
app/src/main/shared/reducers/GlobalState.ts
app/src/test/contrib/components/ChooseGroup/ChooseGroupContentTests.tsx
app/src/test/shared/components/Login/LoginFormTests.tsx

Added a few typings to components. Also a suggested pattern for testing `mapStateToProps` and `mapDispatchToProps` - define as static functions on the component itself, and then can test them in isolation.

Couple of suggestions for typings and tests

---

app/src/integrationTests/ReportIntegrationTests.tsx
app/src/main/report/components/Reports/ReportDetails.tsx
app/src/main/report/components/Reports/ReportPage.tsx
app/src/main/report/components/Reports/Sidebar.tsx
app/src/main/report/styles/reports.scss
app/src/main/shared/components/NavCollapsedOnMobile.tsx

Adds sidebar to report page. At the moment it doesn't do anything - the `Downloads` tab is marked as selected, and the 2 other tabs are disabled with tooltips to let the user know they're 'coming soon'.
Collapses to a burger menu on mobile.

I1518 sidebar

---

app/src/main/report/components/Artefacts/InlineArtefact.tsx
app/src/main/report/components/FileDownloadLink.tsx
app/src/main/report/components/OneTimeLinkContext.tsx
app/src/test/report/components/Artefacts/InlineArtefactTests.tsx
app/src/test/report/components/FileDownloadLinkTests.tsx
app/src/test/report/components/OneTimeLinkContextTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1538

i1538:  Convert `OneTimeLinkContext` to higher-order component

---

app/src/main/report/components/Sidebar/SidebarAdmin.tsx
app/src/test/report/components/Sidebar/SidebarAdminTests.tsx

Bug on prod: report page hangs if the report versions array does not exist

check versions present before component is ready

---

app/src/main/report/components/Reports/ReportPage.tsx
app/src/main/report/components/Sidebar/ReportReadersList.tsx
app/src/test/report/components/Sidebar/ReportReadersListTests.tsx

But first merge https://github.com/vimc/montagu-webapps/pull/209 for a cleaner diff

I1599 - show report readers full names

---

app/src/integrationTests/ReportIntegrationTests.tsx
app/src/main/report/components/Artefacts/ArtefactsSection.tsx
app/src/main/report/components/FileDownloadLink.tsx
app/src/main/report/components/OneTimeLinkContext.tsx
app/src/main/report/components/Reports/ReportDownloads.tsx
app/src/main/shared/components/DownloadIcon.tsx
app/src/test/report/components/Artefacts/ArtefactsSectionTests.tsx
app/src/test/report/components/FileDownloadLinkTests.tsx
app/src/test/report/components/Reports/ReportDownloadsTests.tsx

Moved link to download all files as zip to the bottom of the page and turned it into a button. To do this have added a new component, similar to the download link, using the existing one time context hoc.

I1612 - button to download all files 

---

app/docker/shared-build-env.dockerfile

Track latest version of Node 8. This is in line with the general approach Rich and I discussed of tracking stable upstream releases automatically.

Node latest

---

app/src/@types/Settings.d.ts
app/src/main/contrib/components/Responsibilities/Overview/List/TemplateLinks.tsx
app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewDescription.tsx
app/src/main/shared/settings/default.ts

i1636 - turn rfp touchstone ids into array

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/actions/demographicActionCreators.ts
app/src/main/contrib/services/DemographicService.ts
app/src/test/contrib/actions/DemographicActionsTests.ts
app/src/test/contrib/services/DemographicServiceTests.ts

This fixes a regression that happened during the refactor to redux.

include gender query string

---

app/src/main/admin/components/AdminLoginPage.tsx

switch login page to new redux

---

app/src/main/admin/components/AdminNoRouteFoundPage.tsx
app/src/main/admin/components/AdminRouter.tsx

change no route found to redux

---

app/src/integrationTests/ReportIntegrationTests.tsx
app/src/main/report/actionTypes/OnetimeTokenActions.ts
app/src/main/report/reducers/oneTimeTokenReducer.ts
app/src/main/report/reducers/reportAppReducers.ts
app/src/main/report/services/AbstractReportLocalService.ts
app/src/main/report/services/OneTimeTokenService.ts
app/src/test/mocks/mockStates.ts
app/src/test/report/reducers/onetimeTokenReducerTests.ts

First PR, adding a new service and basic reducer.

add onetime token reducer and service with tests

---

app/src/main/admin/components/AdminRouter.tsx
app/src/main/contrib/components/ContribRouter.tsx
app/src/main/report/components/ReportingRouter.tsx
app/src/test/admin/components/AdminRouterTests.tsx
app/src/test/contrib/components/ContribRouterTests.tsx
app/src/test/report/components/ReportingRouterTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1972

i1972:  Logging onto reporting portal does not take you to your intended destination 

---

app/package-lock.json
app/src/main/contrib/components/Responsibilities/Expectations/CountriesList.tsx
app/src/main/contrib/components/Responsibilities/Expectations/ExpectationsDescription.tsx
app/src/test/contrib/components/Responsibilities/Expectations/CountriesListTests.tsx
app/src/test/contrib/components/Responsibilities/Expectations/ExpectationsDescriptionTests.tsx

Ready for review. UI based on feedback from Katy and Margaret

update expectations UI and tests

---

app/src/main/shared/actionTypes/OnetimeTokenActions.ts
app/src/main/shared/actions/oneTimeTokenActionCreators.ts
app/src/main/shared/reducers/oneTimeTokenReducer.ts
app/src/test/report/actions/onetimeTokenActionCreatorsTests.ts
app/src/test/shared/reducers/onetimeTokenReducerTests.ts

I ran locally and couldn't see a flicker anymore.

remove token before fetching a new one

---

app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
app/src/main/shared/components/UploadFileForm.tsx
app/src/test/shared/components/OneTimeLinkContextTests.tsx
app/src/test/shared/components/UploadFormTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1639

change choose file text on uploadfile form

---

app/src/main/contrib/components/ChooseGroup/ChooseGroupContent.tsx
app/src/main/contrib/components/Responsibilities/Expectations/ExpectationsDescription.tsx
app/src/main/report/style.scss
app/src/main/shared/components/DownloadIcon.tsx
app/src/main/shared/components/FileDownloadLink.tsx
app/src/main/shared/components/NoRouteFound.tsx
app/src/main/shared/styles/buttons.scss
app/src/main/shared/styles/common.scss
app/src/test/contrib/components/Responsibilities/Expectations/ExpectationsDescriptionTests.tsx
app/src/test/shared/components/FileDownloadLinkTests.tsx
app/src/test/shared/components/OneTimeLinkContextTests.tsx

And a bit of opportunistic css tidying up

I2013 - stochastic template button

---

app/src/main/admin/actions/pages/MainMenuPageActionCreators.ts
app/src/main/admin/components/AdminPageHeader.tsx
app/src/main/admin/components/AdminRouter.tsx
app/src/main/admin/components/MainMenu/MainMenu.tsx
app/src/main/contrib/components/ContribPageHeader.tsx
app/src/main/report/components/ReportingPageHeader.tsx
app/src/main/shared/components/PageWithHeader/PageHeader.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1853

i1853: Simplify names

---

app/src/main/shared/components/ForgottenPasswordPage.tsx
app/src/main/shared/components/Login/ForgottenPasswordForm.tsx
app/src/main/shared/components/Login/LoginForm.tsx
app/src/test/shared/components/ForgottenPasswordPageTests.tsx
app/src/test/shared/components/Login/LoginFormTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2023
This isn't really part of the original ticket, but I couldn't resist fixing this while I was here, as it has bugged me for ages. Now if you click "Forgotten password", it will carry over your email from the login form, saving you keystrokes.

i2023: Autofill email

---

app/src/@types/Settings.d.ts
app/src/main/contrib/components/Responsibilities/Expectations/ExpectationsDescription.tsx
app/src/main/contrib/components/Responsibilities/Overview/List/ResponsibilityList.tsx
app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewContent.tsx
app/src/main/shared/models/Generated.ts
app/src/main/shared/settings/default.ts
app/src/main/shared/settings/development.ts
app/src/test/contrib/components/Responsibilities/Expectations/ExpectationsDescriptionTests.tsx
app/src/test/contrib/components/Responsibilities/Overview/ResponsibilityOverviewContentTests.tsx
app/src/test/mocks/mockModels.ts

Behind a switch which is turned on, but easy to turn off if we want to roll back.

I2026 - list scenarios and add link to templates

---

app/src/main/contrib/components/Responsibilities/Guidance/ResponsibilityGuidanceModelInputsPage.tsx

I've added new paragraphs explaining the coverage data format
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1637

i1637: Update ResponsibilityGuidanceModelInputsPage

---

app/src/main/shared/components/OneTimeLinkContext.tsx
app/src/test/shared/components/OneTimeLinkContextTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2088
I think this is the piece that got missed during the enable/loading refactor.

i2088: Disable wrapped one time link component when href is null

---

app/src/main/admin/components/Touchstones/List/TouchstoneListItem.tsx
app/src/test/admin/components/Touchstones/List/TouchstoneListItemTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2095

i2095: Fix link

---

app/scripts/add-test-accounts-for-integration-tests.sh
app/src/integrationTests/AdminIntegrationTests.tsx
app/src/main/admin/actionTypes/ScenarioTypes.ts
app/src/main/admin/actions/scenarioActionCreators.ts
app/src/main/admin/reducers/adminAppReducers.ts
app/src/main/admin/reducers/scenarioReducer.ts
app/src/main/contrib/createStore.ts
app/src/main/shared/services/TouchstonesService.ts
app/src/test/admin/actions/scenarioActionCreatorsTests.ts
app/src/test/admin/reducers/scenarioReducerTests.ts
app/src/test/mocks/mockModels.ts
app/src/test/mocks/mockStates.ts
app/src/test/shared/services/TouchstonesServiceTests.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2102
UI changes will be in parent ticket.

i2102: Service to get scenarios for touchstone 

---

app/src/main/report/LinkHelpers.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2115

i2115: Link to artefact without trailing slash

---

app/src/main/admin/components/Touchstones/Scenarios/ScenarioGroup.tsx
app/src/test/admin/components/Touchstones/Scenarios/ScenarioGroupTests.tsx

Only show disease with scenarios, add more margin between items.

I2117 - scenario list

---

app/src/main/shared/services/AbstractLocalService.ts
app/src/main/shared/services/AuthService.ts

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2111

i2111: Don't send ACAC header on login

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/actionTypes/EstimateTypes.ts
app/src/main/contrib/actions/estimatesActionCreators.ts
app/src/main/contrib/reducers/contribAppReducers.ts
app/src/main/contrib/reducers/estimatesReducer.ts
app/src/main/contrib/services/EstimatesService.ts
app/src/test/contrib/actions/EstimatesActionsTests.ts
app/src/test/contrib/reducers/EstimatesReducerTests.ts
app/src/test/mocks/mockStates.ts

This is a PR just for the service, action creator and reducer needed to get estimates from the API. It will be useful in both https://vimc.myjetbrains.com/youtrack/issue/VIMC-2454 and https://vimc.myjetbrains.com/youtrack/issue/VIMC-2451

I2452 - machinery to get estimates for use in rendering diagnostics

---

app/package-lock.json
app/package.json
app/src/main/shared/components/InternalLink.tsx

Honestly don't really get what this `PropTypes` thing is all about or why leaving out this declaration causes the router not to be attached to the context but this has fixed the routing :woman_shrugging:

add proptypes back in

---

app/package-lock.json
app/src/main/report/components/ReportsList/ReportListTable.tsx
app/src/test/report/components/ReportsList/ReportListTable/ReportListTableTests.tsx

Fixes regression with report versions sorted in the wrong order.

reintroduce sorting with test

---

app/package-lock.json
app/src/main/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetForm.tsx
app/src/test/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetFormTests.tsx

See also https://github.com/vimc/montagu-api/pull/393

VIMC-2985 Remove option to choose type of central burden estimate collection

---

app/package-lock.json
app/src/main/admin/actionTypes/ModellingGroupsTypes.ts
app/src/main/admin/reducers/modellingGroupsReducer.ts
app/src/main/shared/models/Generated.ts
app/src/main/shared/services/ModellingGroupsService.ts
app/src/test/mocks/mockModels.ts
app/src/webmodels/generate/src/main/kotlin/org/vaccineimpact/api/GenerateTypeDefinitions.kt

Once this is merged: https://github.com/vimc/montagu-webmodels/pull/81
can point models submodule back to master

combine model/researchmodel and remove report related models

---

app/package-lock.json
app/src/main/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetForm.tsx
app/src/test/contrib/components/Responsibilities/BurdenEstimates/CreateBurdenEstimateSetFormTests.tsx

Reverts vimc/montagu-webapps#396

Revert "VIMC-2985 Remove option to choose type of central burden estimate collection"

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
app/src/main/contrib/styles/responsibilities.scss

Also fixed the alignment of buttons on the responsibilities overview page cos it looked weird :sweat_smile:

update test to be more flexible

---

app/config/api_version
app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
app/src/main/shared/models/Generated.ts
app/src/test/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummaryTests.tsx
app/src/test/mocks/mockModels.ts

Should only be merged after https://github.com/vimc/montagu-api/pull/403

add filename to current estimate set summary

---

app/src/main/admin/components/ModellingGroups/Models/ModelMetaPage.tsx
app/src/main/admin/components/ModellingGroups/Models/ModelMetaTable.tsx
app/src/main/admin/style.scss
app/src/test/admin/components/ModellingGroups/Models/ModelMetaPageTests.tsx
app/src/test/admin/components/ModellingGroups/Models/ModelMetaTableTests.tsx

Contains changes from https://github.com/vimc/montagu-webapps/pull/404 which should be merged first

Vimc 3085 Show current and obsolete models in separate tables

---

app/src/main/contrib/components/Responsibilities/BurdenEstimates/DiagnosticSection.tsx
app/src/test/contrib/components/Responsibilities/BurdenEstimates/DiagnosticSectionTests.tsx

Hopefully will also fix https://vimc.myjetbrains.com/youtrack/issue/VIMC-3043

Fix bug introduced in VIMC-1222

---

app/src/main/contrib/components/Responsibilities/Expectations/ExpectationsDescription.tsx
app/src/test/contrib/components/Responsibilities/Expectations/ExpectationsDescriptionTests.tsx

https://vimc.myjetbrains.com/youtrack/issue/VIMC-3132

update scenarios to order by description

---

app/src/integrationTests/ContribIntegrationTests.tsx
app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
app/src/test/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummaryTests.tsx

Just commenting out this code until we have time to implement a better fix

hide download button for now

---

app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadEstimateFormComponentTests.tsx

Remove inaccurate "correct your data" message and add a "try again" hint!

change upload error message

---

app/src/@types/Settings.d.ts
app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
app/src/main/shared/settings/default.ts
app/src/test/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummaryTests.tsx

Should be merged after https://github.com/vimc/montagu-api/pull/421

VIMC-3229 enable downloading estimates for all groups

---

app/src/integrationTests/AdminIntegrationTests.tsx

These tests have been failing on master

vimc-3497 Update Admin portal tests for no reports roles

---

.gitignore
app/src/@types/Settings.d.ts
app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewDescription.tsx
app/src/main/shared/settings/default.ts
app/src/main/shared/settings/development.ts
app/src/test/contrib/components/Responsibilities/Overview/ResponsibilityOverviewDescriptionTests.tsx

Hide both guidance links and title span if touchstone is 202005covid

Do not show any guidance links for configured touchstone 202005covid

---

app/README.md
app/scripts/cli.sh

Other PRs:
https://github.com/vimc/montagu-api/pull/434
https://github.com/vimc/montagu-proxy/pull/57

vimc-4292 remove reference to private docker registry

---

app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
app/src/test/contrib/components/Responsibilities/Coverage/DownloadCoverageContentTests.tsx

vimc-4617 Show coverage usage warning message on download page

---

app/package-lock.json
app/package.json
app/scripts/run-dependencies.sh

- Fix issue with `run-dependencies.sh`
- Update `pg` module to current version (8)
- This is a dev dependency used only for integration tests. Previous version (7) refuses to connect to PostgreSQL on my machine.

VIMC-4755 Fix local execution of integration tests

---

app/src/main/shared/settings/default.ts
app/src/test/contrib/components/Responsibilities/Guidance/ResponsibilityGuidanceModelInputsPageTests.tsx
app/src/test/contrib/components/Responsibilities/Guidance/ResponsibilityGuidanceModelOutputsPageTests.tsx

Fix embarrassing error revealed by deployment to UAT

VIMC-4818 Fix guidance displayed for 202108 touchstone

---

app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
app/src/test/admin/components/Touchstones/SingleVersion/TouchstoneResponsibilityPageTests.tsx

To test: visit http://localhost:5000/admin/touchstones/op-2018/op-2018-1/responsibilities/ - there should be no "Export" button at top of page

VIMC-4834 Disable CSV export pending performance review

---

app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
app/src/test/admin/components/Touchstones/SingleVersion/TouchstoneResponsibilityPageTests.tsx
config/api_version

- To test follow instructions on #465
- At time of writing this is also deployed on UAT via [montagu/VIMC-4835](https://github.com/vimc/montagu/tree/VIMC-4835) e.g. [201910gavi-5](https://support.montagu.dide.ic.ac.uk:10443/admin/touchstones/201910gavi/201910gavi-5/responsibilities/)
- Depends on vimc/montagu-api#463
To-do:

VIMC-4835 Resolve CSV export performance issues

---

app/src/main/admin/components/Users/List/UserListItem.tsx
app/src/main/admin/components/Users/List/UsersList.tsx
app/src/test/admin/components/Users/List/UserListItemTests.tsx

Adds a column to the user table which indicates when a user has been inactivated.

show inactive user info on user list page

---

app/src/main/shared/settings/default.ts
app/src/test/shared/settingsTests.ts

Hide guidance for all >= 2022 touchstones

vimc-6722 remove model guidance 
