vimc/montagu-webapps

- app/src/main/admin/stores/AdminAuthStore.ts
- app/src/main/admin/stores/GroupStore.ts
- app/src/main/admin/stores/UserStore.ts
- app/src/main/contrib/stores/ContribAuthStore.ts
- app/src/main/contrib/stores/MainStore.ts
- app/src/main/contrib/stores/ResponsibilityStore.ts
- app/src/main/shared/stores/NotificationStore.ts
See documentation on Typescript 2.4 new concept of 'weak types':
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#weak
The AltJs interface `StoreModel<>` is a 'weak type'. To avoid errors we can use an explicit cast of our stores to this interface when calling `alt.createStore`.
> update code to prevent typescript 2.4 errors

- app/src/test/admin/components/ModellingGroups/SingleGroup/GroupAdminPageTests.tsx
- app/src/test/admin/components/ModellingGroups/SingleGroup/ViewModellingGroupDetailsPageTests.tsx
- app/src/test/contrib/components/ChooseAction/ChooseActionPageTests.tsx
- app/src/test/contrib/components/Responsibilities/DownloadCoveragePageTests.tsx
- app/src/test/contrib/components/Responsibilities/ResponsibilityOverviewPageTests.tsx
- app/src/test/testHelpers.ts
We had a problem where, because of the `setTimeout` in `afterWait`, exceptions thrown were not caught by the `try...catch` statement in `checkAsync`. So we also have to wrap the body of the `afterWait` in a `try...catch`.
> Catch exceptions properly in the afterWait helper

- app/src/main/contrib/stores/Loadable.ts
- app/src/main/contrib/stores/MainStore.ts
- app/src/main/shared/models/Lookup.ts
- app/src/test/contrib/models/LoadableTests.ts
- app/src/test/contrib/stores/MainStoreTests.ts
- app/src/test/contrib/stores/ResponsibilityStoreTests.ts
- app/src/test/mocks/mocks.ts
We have ILookup (which is just a dictionary, or plain JavaScript object).
And then we have `ILoadable`, which is a lookup + a boolean to track whether it has been loaded yet.
Alll the helper functions for `ILoadable` have `ILookup` in the name (e.g. `getFromLookup`), and there is no helper method that just works with a plain `ILookup`.
This PR fixes those problems.
> Stopping calling loadables lookups.

- app/src/main/report/components/Artefacts/Artefact.tsx
- app/src/main/report/components/Resources/ResourceLinks.tsx
- app/src/main/shared/Helpers.ts
- app/src/test/report/components/Artefacts/ArtefactItemTests.tsx
- app/src/test/report/components/Resources/ResourceLinksTest.tsx
update resource and artefact links to use the new encoding for route params - colons in place of slashes
> replace slashes with colons

- app/src/main/admin/components/Users/Create/CreateUserForm.tsx
- app/src/main/admin/components/Users/Create/CreateUserFormStore.ts
- app/src/main/shared/styles/common.css
https://vimc.myjetbrains.com/youtrack/issue/VIMC-585
There's also another small change here: I switched to using notificationActions for errors in the form. This is maybe not ideal UI-wise, but it matches your work on the set password form, and it means that if a redirect occurs (for example if the user's token has expired) they still see the message.
We should have a proper chat at some point about unifying feedback from forms.
> Disable user create form while request is pending

- app/docker/nginx.default.conf
https://vimc.myjetbrains.com/youtrack/issue/VIMC-578
This doesn't actually disable caching; it just ensures that clients check with the server what the latest version is before deciding whether to use their local cached copy or the newer one.
> Turn off caching.

- app/src/main/shared/sources/Source.ts
- app/src/test/shared/fetch/SourceTests.ts
Bug - if the query string on the upload estimate page is empty, jwt_decode throws an error
> extra test and fixed functionality

- app/src/main/admin/components/ModellingGroups/List/ModellingGroupsList.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/Admin/GroupAdminContent.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ModellingGroupDetailsContent.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/ModellingGroupTitle.tsx
- app/src/main/admin/components/Users/List/UsersList.tsx
- app/src/main/admin/components/Users/SingleUser/UserDetailsContent.tsx
- app/src/main/admin/components/Users/SingleUser/UserTitle.tsx
- app/src/main/contrib/components/ChooseAction/ChooseActionContent.tsx
- app/src/main/contrib/components/ChooseGroup/ChooseGroupContent.tsx
- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContent.tsx
- app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
- app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
- app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewContent.tsx
- app/src/main/report/components/Reports/ReportDetails.tsx
- app/src/main/report/components/Reports/ReportList.tsx
- app/src/main/shared/components/OneTimeButton.tsx
- app/src/main/shared/components/RemoteContentComponent/RemoteContentComponent.tsx
- app/src/test/Sandbox.ts
- app/src/test/contrib/components/RemoteContentComponentsTests.tsx
- app/src/test/contrib/components/Responsibilities/DownloadCoverageComponentTests.tsx
- app/src/test/shared/components/OneTimeButtonTests.tsx
* to do this i needed to use local state on DownloadCoverageContentComponent
* to use local state i needed to create proper state interface for this component
* to do this i needed to change parent component RemoteContentComponent to be able to accept state interface
* this change made me change all components using RemoteContentComponent as parent
* now local state interface can be used if needed for all of them
* had to fix some tests
> i586 - on click download button it will be disabled for 5 seconds

- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContent.tsx
- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadForm.tsx
- app/src/test/contrib/components/Responsibilities/Uploads/UploadEstimatesContentTests.tsx
- app/src/test/contrib/components/Responsibilities/Uploads/UploadFormTests.tsx
Noticed that `UploadForm` no longer uses `groupId` or `scenarioId` so have removed these from its props.
> remove unused props

- app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ViewModellingGroupDetailsPage.tsx
- app/src/main/admin/components/Users/SingleUser/ViewUserDetailsPage.tsx
- app/src/main/contrib/components/ChooseAction/ChooseActionPage.tsx
- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesPage.tsx
- app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoveragePage.tsx
- app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewPage.tsx
- app/src/main/shared/components/NavBar/NavBar.css
Should have the page entity name in the breadcrumb.
for example:
in Contrib: 
Url: 
/IC-Garske/responsibilities/op-2017-2/coverage/yf-routine/
Breadcrumb:
Modellers' contribution portal> IC-Garske > op-2017-2 > yf-routine
In Admin:
Url: 
/users/test.user/
Breadcrumb:
Main menu > Users > test.user
> I1006 - Should have the page entity name in the breadcrumb.

- app/src/main/shared/models/Generated.ts
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1173
Needs pointing back at webmodels master after https://github.com/vimc/montagu-webmodels/pull/34 is merged.
> i1173: Update responsibility set status

- app/src/test/contrib/stores/ContribAuthStoreTests.ts
https://vimc.myjetbrains.com/youtrack/issue/VIMC-652
Turns out this bug has already been fixed in the past. This PR adds a test that proves the correct behaviour is present.
> i652: If user is a member of non-existent modelling group, the modelling group portal will not load 

- app/src/integrationTests/ContribIntegrationTests.tsx
- app/src/main/contrib/components/Responsibilities/ModelRunParameters/ModelRunParametersForm.tsx
- app/src/main/shared/models/Generated.ts
- app/src/test/contrib/components/Responsibilities/ModelRunParameters/ModelRunParametersFormTests.tsx
- app/src/test/mocks/mockModels.ts
Some integration tests were trying to populate the dropped 'description' column on the model run parameters table.
Also removed the empty description field from the upload form
> update integration tests

- app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewContent.tsx
We should show the stochastic parameters section if the touchstone Id is not an rfp touchstone, OR if it is a stochastic touchstone.
> show params section if touchstone is non rfp, or is stochastic

- app/src/main/report/components/ReportsList/ReportListColumns/VersionColumn.tsx
- app/src/main/report/components/ReportsList/ReportListTable.tsx
- app/src/test/report/components/ReportsList/ReportListTable/LatestVersionColumnTests.tsx
Add a custom sorter for the date so that the default sorting is descending, not ascending. Make the table sorted by date on page load. Flip the id and the date in the latest version cell.
> sort by date by default

- app/src/main/admin/actions/pages/usersListPageActionCreators.ts
- app/src/main/admin/components/AdminRouter.tsx
- app/src/main/admin/components/Users/Create/CreateUserForm.tsx
- app/src/main/admin/components/Users/List/UsersList.tsx
- app/src/main/admin/components/Users/List/UsersListPage.tsx
- app/src/main/admin/components/Users/List/ViewAllUsersPage.tsx
- app/src/main/admin/components/Users/SingleUser/ViewUserDetailsPage.tsx
- app/src/main/shared/actions/breadcrumbsActionsCreators.ts
- app/src/test/admin/actions/pages/userPageActionCreatorTests.ts
- app/src/test/admin/components/Users/List/UserListPageTests.tsx
- app/src/test/admin/components/Users/List/UsersListComponentTests.tsx
- app/src/test/admin/components/Users/List/ViewAllUsersPageTests.tsx
- app/src/test/mocks/mockStates.ts
First PR that breaks down some of branch i1737 with tests added. 
This PR just adds a new redux component `UserListPage` and refactors the `UserListComponent`. It leaves a lot of `altjs` machinery alongside the new redux code, but this will be removed incrementally in further PRs.
> i1737 - user list component and page

- app/src/main/admin/components/Users/Create/CreateUserSection.tsx
- app/src/main/admin/reducers/usersReducer.ts
- app/src/main/shared/components/ReduxForm/ReduxFormValidationError.tsx
- app/src/test/admin/components/Users/Create/CreateUserSectionTests.tsx
- app/src/test/admin/reducers/UsersReducerTests.ts
- app/src/test/mocks/mockStates.ts
- app/src/test/shared/components/ReduxFormValidationErrorsTests.tsx
The error wasn't showing due to a typo. The success feedback is just that the user is added to the list (and the create user section closed) - this is the status quo before this refactor, so if we want to change this behaviour I suggest opening another ticket to do so.
> typo fix and test

- app/src/main/report/actions/OneTimeTokenActions.ts
- app/src/main/report/models/OneTimeToken.ts
- app/src/main/report/stores/OneTimeTokenStore.ts
- app/src/test/report/fetch/OneTimeTokenFetchTests.ts
- app/src/test/report/stores/OnetimeTokenStoreTests.ts
We were inflating the reporting API's one time token before passing it back in requests, defeating the whole object of the compressed token!
Note that with the changes made here and in VIMC-1938 and VIMC-1942, we are now storing the compressed token in local storage and in the altjs store, which may make debugging slightly harder in the event that something goes wrong and we want to inspect those tokens. I don't think it's a big deal for now, but if we do find this inconveniencing us down the line we could store both the compressed and the decompressed token each time.
> use compressed token as one time token for report endpoints

- app/src/main/contrib/ContribPage.tsx
- app/src/main/contrib/actions/pages/ContribPageActionCreators.ts
- app/src/main/contrib/actions/pages/chooseGroupPageActionCreators.ts
- app/src/main/contrib/components/ChooseGroup/ChooseGroupPage.tsx
- app/src/main/report/components/OneTimeLinkContext.tsx
- app/src/main/shared/components/Page.tsx
- app/src/test/ActionCreatorTestHelpers.ts
- app/src/test/contrib/actions/pages/ChooseGroupPageActionsTests.ts
- app/src/test/contrib/components/ChooseGroup/ChooseGroupPageTests.tsx
- app/src/test/mocks/mocks.ts
- app/src/test/shared/components/PageTests.tsx
This refactors the top-level page in the Contrib portal, `ChooseActionPage`, to use the new `AbstractPageActionCreators` class, and also adds a new HOC that can be used to hook up an instance of the `AbstractPageActionCreators` class to a page component by automatically calling the former's `onLoad` method when the component mounts.
> migrate contrib page action creators to new style

- app/src/main/contrib/components/Responsibilities/Demographics/DownloadDemographicsContent.tsx
- app/src/main/shared/components/FileDownloadLink.tsx
- app/src/main/shared/components/OneTimeLinkContext.tsx
- app/src/test/shared/components/FileDownloadLinkTests.tsx
- app/src/test/shared/components/OneTimeLinkContextTests.tsx
Removes `enabled` prop passed to `OnetimeLinkContext` and introduces `loading` prop generated by the HOC and passed to the wrapped component.
> I2042 alex suggestions

- app/src/test/shared/services/LocalServiceTests.ts
Tiny refactor I wanted to keep separate from the VIMC-2092 work, as it involves a lot of whitespace changes. This just makes the tests a bit more idiomatic mocha, by instead of having three completely different test fixtures, uses one test fixture with three nested test fixtures. This makes the test output a bit easier to understand.
> Restructure LocalServiceTests to use nested describe.

- app/src/main/admin/components/Touchstones/Scenarios/ScenarioGroup.tsx
- app/src/main/admin/components/Touchstones/Scenarios/ScenariosList.tsx
- app/src/test/admin/components/Touchstones/Scenarios/ScenarioGroupTests.tsx
- app/src/test/admin/components/Touchstones/Scenarios/ScenariosListTests.tsx
- app/src/test/mocks/mockStore.ts
Show them as disabled with explanatory tooltip if user does not have global coverage reading permission.
> i2082 - add links to download coverage

- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContent.tsx
- app/src/main/shared/settings/docker.ts
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContentTests.tsx
Also update the section on the burden estimate upload page with a link to the new templates page.
Note this PR turns new template links on, so once merged, a deploy will expose new templates to all users.
> I2136 - turn new templates on

- app/src/main/admin/components/Touchstones/Scenarios/ScenarioGroup.tsx
- app/src/main/admin/components/Touchstones/Scenarios/ScenariosList.tsx
- app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
- app/src/main/shared/components/Demographics/DemographicOptions.tsx
- app/src/test/admin/components/Touchstones/Scenarios/ScenarioGroupTests.tsx
- app/src/test/contrib/components/Responsibilities/Coverage/DownloadCoverageContentTests.tsx
- app/src/test/shared/components/Demographics/DemographicOptionsTests.tsx
Not sure if putting the format guidance in tooltips is the right thing (but is consistent with countries guidance in the case of coverage data). Maybe don't need it at all in Admin any more? (Tooltips on the buttons might get a bit annoying?)
> Added tooltips with guidance on file format

- app/src/main/report/components/Sidebar/Sidebar.tsx
The changelog link had somehow re-acquired its id (previously used as a target for the 'coming soon' tooltip), so the anchor was acting like an anchor!
> Removing id from changelog link

- app/docker-compose.yml
As discussed yesterday, the webapps should use orderly.server not montagu-orderly for testing
The image is much smaller and built more often
> i2772: Use the smaller container

- app/src/main/contrib/components/Responsibilities/BurdenEstimates/PopulateBurdenEstimatesForm.tsx
- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
- app/src/main/report/components/ReportsList/ReportListTable.tsx
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/PopulateBurdenEstimateFormComponentTests.tsx
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimateFormTests.tsx
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesContentTests.tsx
As I was testing on UAT it came to my attention that bc of the weird 2 step form the error/success alerts after uploading a set of estimates were in the wrong place. 
They should live one component level up from the `PopulateBurdenEstimatesForm`, in the component that renders both that and the `CreateBurdenEstimateSetForm`. This component was still expecting error/success messages to come from a query string, so have changed it over to look in the store state instead.
> VIMC-2796 move success and error alerts to top level component

- app/docker/shared-build-env.dockerfile
Some package update is breaking everything, possibly because of a memory leak:
http://teamcity.montagu.dide.ic.ac.uk:8111/viewLog.html?buildId=43316&buildTypeId=montagu_webapps_build_contrib
Seeing as we are actually using a package-lock file, I've just changed the build environment to install dependencies from there to pin the versions. I will try to work out which package broke things and whether it's a bug or whether we really should increase the memory allocated to node, but for now lets just pin dependencies.
Upgraded webpack while I was at it.
> Upgrade webpack and fix dependencies

- app/src/main/contrib/actions/pages/uploadBurdenEstimatesPageActionCreators.ts
- app/src/test/contrib/actions/pages/UploadBurdenEstimatesPageActionsTests.ts
This should fix this bug, but see related issue https://vimc.myjetbrains.com/youtrack/issue/VIMC-2978
UPDATE: can't seem to reproduce this other bug at all now!
> Vimc 2911 Bugfix: success message persists after navigating away from burden estimate upload page 

- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/main/admin/actionTypes/ModellingGroupsTypes.ts
- app/src/main/admin/actions/modellingGroupsActionCreators.ts
- app/src/main/admin/actions/pages/ModelMetaPageActionCreators.ts
- app/src/main/admin/components/AdminRouter.tsx
- app/src/main/admin/components/ModellingGroups/Models/ModelMetaPage.tsx
- app/src/main/admin/components/ModellingGroups/Models/ModelMetaTable.tsx
- app/src/main/admin/reducers/modellingGroupsReducer.ts
- app/src/main/contrib/reducers/modellingGroupsReducer.ts
- app/src/main/shared/services/ModellingGroupsService.ts
- app/src/main/shared/styles/common.scss
- app/src/test/admin/actions/ModellingGroupsActionsTests.ts
- app/src/test/admin/actions/pages/ModelMetaPageActionsTests.ts
- app/src/test/admin/components/ModellingGroups/Models/ModelMetaPageTests.tsx
- app/src/test/admin/components/ModellingGroups/Models/ModelMetaTableTests.tsx
- app/src/test/admin/reducers/ModellingGroupsReducerTests.ts
- app/src/test/mocks/mockModels.ts
This adds a super simple table with the existing model meta. To be extended once the richer endpoints have been added.
Note this adds the route so it can be viewed by manually navigating to the url `/modelling-groups/models/` but does not link it from anywhere, idea being we wait til it's finished to actually link to it.
> model meta table with the basic model info that we have

- app/config/api_version
- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/main/admin/components/ModellingGroups/Models/ModelMetaTable.tsx
- app/src/main/admin/style.scss
- app/src/main/contrib/components/Responsibilities/Expectations/ExpectationsDescription.tsx
- app/src/main/shared/models/Generated.ts
- app/src/main/shared/styles/common.scss
- app/src/test/admin/components/ModellingGroups/Models/ModelMetaTableTests.tsx
- app/src/test/contrib/components/Responsibilities/Expectations/ExpectationsDescriptionTests.tsx
- app/src/test/mocks/mockModels.ts
- app/src/test/shared/components/PageArticleTests.tsx
Contains changes from https://github.com/vimc/montagu-webapps/pull/401 which should be merged first
> Vimc 3081 show model metadata outcome details in tooltip

- app/src/main/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummary.tsx
- app/src/test/contrib/components/Responsibilities/Overview/List/CurrentEstimateSetSummaryTests.tsx
We don't have the filename stored for old estimate sets. We shouldn't show the filename messages when the filename is null.
> don't show filename if it doesn't exist

- app/src/main/contrib/actions/estimatesActionCreators.ts
- app/src/main/contrib/components/Responsibilities/BurdenEstimates/UploadBurdenEstimatesForm.tsx
- app/src/main/contrib/reducers/estimatesReducer.ts
- app/src/test/contrib/actions/EstimatesActionsTests.ts
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadEstimateFormComponentTests.tsx
- app/src/test/contrib/components/Responsibilities/BurdenEstimates/UploadEstimateFormTests.tsx
This fixes the following bug:
1. upload a file through the burden estimate upload form
2. change the metadata (or do nothing) and hit upload again without changing the file
3. upload button gets greyed out but nothing happens
> fix issues with form upload

- app/src/main/shared/components/Demographics/DownloadDemographicsContent.tsx
This is now correct for the 201910test-1 and 201910gavi-1 touchstones. I suppose really this text should be specific to the demographic data being downloaded, but that's more work than we'd want to do right now.
> Update demography text

- app/src/@types/Settings.d.ts
- app/src/main/contrib/components/Responsibilities/Coverage/DownloadCoverageContent.tsx
- app/src/main/shared/settings/default.ts
- app/src/test/contrib/components/Responsibilities/Coverage/DownloadCoverageContentTests.tsx
- app/src/test/shared/settingsTests.ts
Wide format has a bug for campaign data, so we're hiding the format control for all diseases that have campaigns in the latest touchstone until this is fixed.
> VIMC-3254 hide wide format

- app/config/api_version
- app/src/main/shared/actions/demographicActionCreators.ts
- app/src/test/admin/actions/pages/DownloadDemographicPageActionsTests.ts
- app/src/test/contrib/actions/pages/DownloadDemographicPageActionsTests.ts
- app/src/test/shared/actions/DemographicActionsTests.ts
Reported by Wes: https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-3209
Problem was the selected data set wasn't being updated when the touchstone changed, so would have a dataset belonging to the wrong touchstone selected.
> vimc-3209 bug when changing touchstones and downloading demographics

- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/integrationTests/IntegrationTest.ts
Same issue as with the API - integration tests failing since [this db change](https://github.com/vimc/montagu-db/commit/732ae2e021a6bab16c85195aa432cf1cd2588df5)
> VIMC-4119 update integration tests after breaking db change

- buildkite/pipeline.yml
- buildkite/run-build.sh
Docker containers brought up during the build should be removed in the same step, when the script for that build step exits.
> vimc-4150 trap exit and clean up containers

- app/src/main/admin/actions/usersActionCreators.ts
- app/src/test/admin/actions/UsersActionsTests.ts
Could have done in this in the api, but I figured it was valid to return this system user, we just don't want it being viewable in the portal.
> vimc-4240 Exclude MONTAGU_TASK_QUEUE user from the user management page

- app/src/main/admin/components/Touchstones/List/TouchstoneList.tsx
- app/src/main/admin/components/Touchstones/List/TouchstoneListItem.tsx
- app/src/main/admin/components/Touchstones/List/TouchstoneTable.tsx
- app/src/test/admin/components/Touchstones/List/TouchstoneListItemTests.tsx
- app/src/test/admin/components/Touchstones/List/TouchstoneListTests.tsx
- app/src/test/admin/components/Touchstones/List/TouchstoneTableTests.tsx
It's possible for a touchstone to have a previous version in un-finished status even though the most recent version is marked as "finished", e.g.
https://montagu.vaccineimpact.org/admin/touchstones/201907wue/
In this case the latest, finished, version should not be linked in the table of "active" touchstones: 
https://montagu.vaccineimpact.org/admin/touchstones/
nb: some of these cases are probably in error, we should also pick up this ticket to allow admins to easily mark touchstones as finished: https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-10
> vimc-4325 don't show finished touchstones in active touchstone list

- app/src/main/admin/components/AdminApp.tsx
- app/src/main/admin/components/AdminRouter.tsx
- app/src/main/shared/components/App.ts
- app/src/main/shared/reducers/authReducer.ts
- app/src/test/admin/components/AdminAppTests.tsx
- app/src/test/admin/components/AdminRouterTests.tsx
- app/src/test/mocks/mockStates.ts
- app/src/test/shared/reducers/AuthReducersTests.ts
Interestingly, what this ticket has revealed is that, in fact, we do not currently lock down any other routes in the portals! We just strategically hide links to the pages, and the user who stumbles on a route they shouldn't find will just have a bad time, because the API which is serving the data will return 401s when the portal requests it. 
I think we got away with this before, when the modellers accessing the contrib portal, and admin users accessing the admin portal would probably all have much the same sets of permissions, but now that we'll be opening the Admin portal to GAVI users with restricted privileges to upload coverage only we should probably be more stringent. 
Making this ticket a proof of concept for putting this in for the coverage route, and have made another ticket …
> vimc-4433 Restrict coverage route to users with coverage-write permission

- app/src/main/admin/components/Touchstones/Coverage/CoverageVariablesPage.tsx
Update text of the guidance page to indicate that years 2000 - 2100 are accepted, and 2021 - 2030 are mandatory
> vimc-4451 Update guidance for accepted years

- app/README.md
- app/src/main/admin/actions/pages/UserDetailsPageActionCreators.ts
- app/src/main/admin/components/MainMenu/MainMenu.tsx
- app/src/main/admin/components/ModellingGroups/Create/CreateModellingGroupSection.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/Details/ModellingGroupDetailsContent.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/Members/ModellingGroupMembersContent.tsx
- app/src/main/admin/components/ModellingGroups/SingleGroup/Members/ModellingGroupMembersList.tsx
- app/src/main/admin/components/Touchstones/Scenarios/ScenariosList.tsx
- app/src/main/admin/components/Users/Create/CreateUserSection.tsx
- app/src/main/admin/components/Users/SingleUser/UserDetailsContent.tsx
- app/src/main/shared/reducers/authReducer.ts
- app/src/test/admin/actions/pages/UserDetailsPageActionCreatorTests.ts
- app/src/test/admin/components/MainMenuTests.tsx
- app/src/test/admin/components/ModellingGroups/SingleGroup/Details/ModellingGroupDetailsContentTests.tsx
- app/src/test/admin/components/ModellingGroups/SingleGroup/Members/ModellingGroupMembersContentTests.tsx
- app/src/test/admin/components/ModellingGroups/SingleGroup/Members/ModellingGroupMembersListTests.tsx
- app/src/test/admin/components/Touchstones/Scenarios/ScenariosListTests.tsx
- app/src/test/admin/components/Users/Create/CreateUserSectionTests.tsx
- app/src/test/admin/components/Users/SingleUser/UserDetailsComponentTests.tsx
- app/src/test/mocks/mockStates.ts
- app/src/test/shared/reducers/AuthReducersTests.ts
Remove permissions as a property on auth state, and put all knowledge of individual permissions and the abilities they confer into the state, and use these properties in the components. 
This is preparatory for using these same properties in the router to hide pages from users who should not have access to them
> vimc-4461 Put canDoThing properties on auth state rather than components

- app/src/main/admin/components/AdminRouter.tsx
- app/src/test/admin/components/AdminRouterTests.tsx
Does not include these pages in the router when user does not have */users.read permission. 
Can be tested manually by commenting out `$here/cli.sh addRole test.user admin` in the script `add-test-accounts-for-integration-tests.sh` before running the dependencies - browsing to these pages should now show a 'Page not found' page rather than 'You do not have sufficient permissions' errors and endless spinner.
> vimc-4545 Users without permission should get 404s on user list and details pages

- docker-compose.yml
Adds redis message queue and flower to docker compose for dev dependencies. Without them, an error is shown on burden estimate upload when the API tries to put a message on the queue to kick off a diagnostic report. 
This error probably shouldn't be shown to user anyway as it indicates a problem with montagu infrastucture rather than a problem with the user's upload. This would be a fix in API. But this helps with testing for now.
Test this fix by uploading the burden estimates csv file in the attached zip in the contribution portal, for op-2017-2 touchstone, routine scenario. No error should be shown.
[dummyDEVcentral-burden-template.op-2017-2.description (1).zip](https://github.com/vimc/montagu-webapps/files/5888385/dummyDEVcentral-burden-template.op-2017-2.description.1.zip)
> vimc-4546 Add mq and flower to docker compose file

- app/scripts/run-dependencies.sh
- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/main/admin/actions/adminTouchstoneActionCreators.ts
- app/src/main/admin/actions/pages/TouchstoneResponsibilityPageActionCreators.ts
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityCommentModal.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityList.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityListItem.tsx
- app/src/main/admin/models/AnnotatedResponsibility.ts
- app/src/main/admin/reducers/adminTouchstoneReducer.ts
- app/src/main/shared/actionTypes/TouchstonesTypes.ts
- app/src/main/shared/models/Generated.ts
- app/src/main/shared/services/TouchstonesService.ts
- app/src/main/shared/styles/bootstrap.scss
- app/src/test/admin/actions/AdminTouchstoneActionTests.ts
- app/src/test/admin/actions/pages/TouchstoneResponsibilitiesPageActionTests.ts
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilityCommentModalTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilityListItemTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilityListTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/TouchstoneResponsibilityPageTests.tsx
- app/src/test/admin/reducers/adminTouchstoneReducerTests.ts
- app/src/test/contrib/components/Responsibilities/Overview/List/ResponsibilityListTests.tsx
- app/src/test/mocks/mockModels.ts
- app/src/test/shared/services/TouchstonesServiceTests.ts
- app/src/webmodels/generate/src/main/kotlin/org/vaccineimpact/api/GenerateTypeDefinitions.kt
- config/api_version
- config/db_version
Summary:
* Fix build: has been failing since https://github.com/vimc/orderly/blame/master/inst/create_orderly_demo.sh#L8
* Fix test: [sorting](https://github.com/vimc/montagu-webapps/blob/master/app/src/main/contrib/components/Responsibilities/Overview/List/ResponsibilityList.tsx#L34) of scenarios without descriptions non-deterministic
* Add modal to allow comments to be created/reviewed
* Requires vimc/montagu-db#159 and vimc/montagu-api#458
To test:
* Spin up the admin app, visit http://localhost:5000/admin/touchstones/op-2018/op-2018-1/responsibilities/ and add some comments
To-do:
> VIMC-4734 Add comments to responsibilities

- app/README.md
- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/main/admin/actions/pages/TouchstoneResponsibilityPageActionCreators.ts
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityList.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityListItem.tsx
- app/src/main/shared/reducers/authReducer.ts
- app/src/main/shared/services/TouchstonesService.ts
- app/src/test/admin/actions/pages/TouchstoneResponsibilitiesPageActionTests.ts
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilityListItemTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilityListTests.tsx
- app/src/test/mocks/mockStates.ts
- app/src/test/shared/reducers/AuthReducersTests.ts
- app/src/test/shared/services/TouchstonesServiceTests.ts
- Ensure that touchstone responsibility page renders correctly
- If you have `responsibilities.review` permission (i.e. the typical situation of having the `admin` role) then you see the comments column and can add/edit comments
- If you just don't have that permission (i.e. you have the `user` role) then the page loads regardless but you can't see the column. The endpoint itself is already protected.
- You can test this by running the app, visiting (e.g.) [this page](http://localhost:5000/admin/touchstones/op-2017/op-2017-2/responsibilities/) and checking you can add/edit comments. Then remove `admin` role from `test.user` and revisit the page:
```sh
docker exec -it montagu_db_1 psql -Uvimc montagu -c "delete from user_group_role where role = 17"
```
- This PR also updates URL of …
> VIMC-4775 Remove admin role assumption from responsibilities view

- app/src/integrationTests/AdminIntegrationTests.tsx
- app/src/main/admin/actions/adminTouchstoneActionCreators.ts
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/CommentModal.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityCommentModal.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilityListItem.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitySet.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitySetCommentModal.tsx
- app/src/main/admin/models/AnnotatedResponsibility.ts
- app/src/main/admin/reducers/adminTouchstoneReducer.ts
- app/src/main/shared/actionTypes/TouchstonesTypes.ts
- app/src/main/shared/models/Generated.ts
- app/src/main/shared/services/TouchstonesService.ts
- app/src/test/admin/actions/AdminTouchstoneActionTests.ts
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilitySetCommentModalTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/ResponsibilitySetTests.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/TouchstoneResponsibilityPageTests.tsx
- app/src/test/admin/reducers/adminTouchstoneReducerTests.ts
- app/src/test/mocks/mockModels.ts
- app/src/test/shared/services/TouchstonesServiceTests.ts
- Allow comments to be added to responsibility sets, similar to existing functionality for responsibilities
- Main changes to existing code are splitting out new `ResponsibilitySet` and `CommentModal` components - the latter is shared between logic to comment on responsibilities and responsibility sets, and now auto-focuses the textarea
- To test, visit a touchstone version such as http://localhost:5000/admin/touchstones/op-2017/op-2017-2/responsibilities/ - you should be able to add a comment to each responsibility set (there is only one in this case)
- If you remove the test user's permission to annotate responsibility (sets) as [here](https://github.com/vimc/montagu-webapps/pull/464#issue-688714751) then the comment should disappear if you reload the page
> VIMC-4767 Add comments to responsibility sets

- app/src/main/shared/settings/default.ts
- app/src/test/contrib/components/Responsibilities/Coverage/DownloadCoverageContentTests.tsx
Adds cholera and typhoid to the list of diseases for which wide format coverage is hidden in the Contribution portal. 
Also expands the test of the hidden format control to include all diseases in the list. 
This branch is deployed to UAT, and the easiest way to test it is on there. Add yourself to relevant modelling groups through the Admin portal. You should see that Typhoid and Cholera are now included in those diseases where browsing to touchstone / Download coverage data does not show a format picker. Download should provide long format (a row for each year). Contrast the view for disease not included in this list, e.g. Rota, where format picker should be shown
Example modelling groups:
Typhoid: Yale (Ginny Pitzer)
Cholera: IVI (Jong Hoon-Kim)
Rota: Emory University (Ben Lopman)
> VIMC-4814 Hide wide format coverage for cholera and typhoid

- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/CommentModal.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitiesPage.tsx
- app/src/main/admin/components/Touchstones/SingleTouchstoneVersion/ResponsibilitySet.tsx
- app/src/test/admin/components/Touchstones/SingleVersion/TouchstoneResponsibilityPageTests.tsx
- config/api_version
To test:
- Run admin app and visit the responsibilities page for a touchstone version e.g. http://localhost:5000/admin/touchstones/op-2018/op-2018-1/responsibilities/
- Optionally add some comments to the responsibility set and/or its responsibilities
- Optionally upload some burden estimates via contrib app
- See [central-burden-template.op-2018-1.yf-routine.partial.csv](https://github.com/vimc/montagu-webapps/files/6960042/central-burden-template.op-2018-1.yf-routine.partial.csv) for a burden estimate set with two missing estimates
- Click the "Responsibilities summary" button
- Example output: [responsibilities_op-2018-1.csv](https://github.com/vimc/montagu-webapps/files/6967421/responsibilities_op-2018-1.csv)
Notes:
- Depends on vimc/montagu-api#461
To-do:
> VIMC-4737 Export responsibilities summary for a touchstone

- app/src/main/contrib/components/Responsibilities/Overview/ResponsibilityOverviewDescription.tsx
- app/src/test/contrib/components/Responsibilities/Overview/ResponsibilityOverviewDescriptionTests.tsx
For stochastic touchstones, remove text implying that stochastic data will be uploadable via the portal 'in the future'.
Remove reference to montagu slack channel from default responsibility description contact section.
> vimc-4870 Remove obsolete text from responsibilities page

- app/src/main/shared/components/Demographics/DownloadDemographicsContent.tsx
- app/src/test/shared/components/Demographics/DownloadDemographicContentTests.tsx
This PR makes the text on the demographic download page a bit more general, removing the explicit year, to avoid "2019" appearing on the new page that users will see when downloading the 2022 demography (see [vimc-7116 branch in montagu-imports](https://github.com/vimc/montagu-imports/pull/167)
Perhaps at some point we could make it so that we can vary this message depending on demographic dataset...
I'm not sure whether there is a verson no. that needs bumping...?
> Update demography text - make general
